version: "3.9"

services:

  web:
    image: robotreviewer
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./robotreviewer/data:/var/lib/deploy/robotreviewer/data
    configs:
      - source: rr-config
        target: /var/lib/deploy/robotreviewer/config.json
    restart: unless-stopped
    command: web
    ports:
      - 5050:5000
    depends_on:
      - celery

  api:
    image: robotreviewer
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./robotreviewer/data:/var/lib/deploy/robotreviewer/data
    configs:
      - source: rr-config
        target: /var/lib/deploy/config.json
    restart: unless-stopped
    command: api
    ports:
      - 5051:5001
    depends_on:
      - celery

  celery:
    image: robotreviewer
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./robotreviewer/data:/var/lib/deploy/robotreviewer/data
    configs:
      - source: rr-config
        target: /var/lib/deploy/robotreviewer/config.json
    restart: unless-stopped
    command: celery
    depends_on:
      - rabbitmq
      - bert
      - grobid

  bert:
    image: robotreviewer-bert
    build: ./bert
    environment:
      - SCIBERT_PATH_MODEL=/var/lib/deploy/robotreviewer/data/scibert_scivocab_uncased
    volumes:
      - ./robotreviewer/data:/var/lib/deploy/robotreviewer/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-alpine
    restart: unless-stopped
    volumes:
      - ./rabbitmq/:/etc/rabbitmq/

  grobid:
    image: grobid/grobid:0.6.2
    restart: unless-stopped

configs:
  rr-config:
    file: ./robotreviewer/config.json
